export const POSTS = [
	{
		_id: "1",
		text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
		img: "/posts/post1.png",
		user: {
			username: "varu",
			profileImg: "/avatars/boy1.png",
			fullName: "Vardhini",
		},
		comments: [
			{
				_id: "1",
				text: "Hi Guys",
				user: {
					username: "vams",
					profileImg: "/avatars/girl1.png",
					fullName: "vamsi",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
			username: "varu",
			profileImg: "/avatars/boy2.png",
			fullName: "Vardhini",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "vams",
					profileImg: "/avatars/girl2.png",
					fullName: "vamsi",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "/posts/post2.png",
		user: {
			username: "varu",
			profileImg: "/avatars/boy3.png",
			fullName: "Vardhini",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "/posts/post3.png",
		user: {
			username: "varu",
			profileImg: "/avatars/boy3.png",
			fullName: "Vardhini",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "vams",
					profileImg: "/avatars/girl3.png",
					fullName: "vamsi",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];

export const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		fullName: "vardhini",
		username: "varu",
		profileImg: "/avatars/girl1.png",
	},
	{
		_id: "2",
		fullName: "Ram",
		username: "ram",
		profileImg: "/avatars/boy3.png",
	},
	{
		_id: "3",
		fullName: "sunitha",
		username: "suni",
		profileImg: "/avatars/girl2.png",
	},
	{
		_id: "4",
		fullName: "Vamsi",
		username: "vams",
		profileImg: "/avatars/boy2.png",
	},
];